local E, L, V, P, G = unpack(ElvUI);
local LUI = E:GetModule("Leyo UI");
local classColor = E:ClassColor(E.myclass, true);


function LUI:SetupUnitfames()
	E.db["unitframe"]["colors"]["colorhealthbyvalue"] = false
	E.db["unitframe"]["colors"]["healthclass"] = true
	E.db["unitframe"]["font"] = "Montserrat"
	E.db["unitframe"]["fontOutline"] = "THICKOUTLINE"
	E.db["unitframe"]["fontSize"] = 15
	E.db["unitframe"]["statusbar"] = "Melli"
	E.db["unitframe"]["units"]["boss"]["health"]["text_format"] = ""
	E.db["unitframe"]["units"]["boss"]["power"]["enable"] = false
	E.db["unitframe"]["units"]["party"]["debuffs"]["anchorPoint"] = "LEFT"
	E.db["unitframe"]["units"]["party"]["health"]["text_format"] = ""
	E.db["unitframe"]["units"]["party"]["power"]["text_format"] = ""
	E.db["unitframe"]["units"]["party"]["roleIcon"]["position"] = "LEFT"
	E.db["unitframe"]["units"]["party"]["roleIcon"]["size"] = 25
	E.db["unitframe"]["units"]["party"]["roleIcon"]["xOffset"] = -30
	E.db["unitframe"]["units"]["party"]["showPlayer"] = false
	E.db["unitframe"]["units"]["player"]["RestIcon"]["enable"] = false
	E.db["unitframe"]["units"]["player"]["aurabar"]["enable"] = false
	E.db["unitframe"]["units"]["player"]["buffs"]["attachTo"] = "FRAME"
	E.db["unitframe"]["units"]["player"]["buffs"]["countFont"] = "Montserrat"
	E.db["unitframe"]["units"]["player"]["castbar"]["enable"] = false
	E.db["unitframe"]["units"]["player"]["castbar"]["width"] = 220
	E.db["unitframe"]["units"]["player"]["classbar"]["enable"] = false
	E.db["unitframe"]["units"]["player"]["debuffs"]["attachTo"] = "BUFFS"
	E.db["unitframe"]["units"]["player"]["debuffs"]["countFont"] = "Montserrat"
	E.db["unitframe"]["units"]["player"]["health"]["position"] = "BOTTOMRIGHT"
	E.db["unitframe"]["units"]["player"]["health"]["text_format"] = "[health:current:shortvalue]"
	E.db["unitframe"]["units"]["player"]["health"]["xOffset"] = 3
	E.db["unitframe"]["units"]["player"]["health"]["yOffset"] = -17
	E.db["unitframe"]["units"]["player"]["height"] = 26
	E.db["unitframe"]["units"]["player"]["name"]["position"] = "TOPLEFT"
	E.db["unitframe"]["units"]["player"]["name"]["text_format"] = "[name:short]"
	E.db["unitframe"]["units"]["player"]["name"]["yOffset"] = 15
	E.db["unitframe"]["units"]["player"]["power"]["detachedWidth"] = 74
	E.db["unitframe"]["units"]["player"]["power"]["enable"] = false
	E.db["unitframe"]["units"]["player"]["raidRoleIcons"]["position"] = "TOPRIGHT"
	E.db["unitframe"]["units"]["player"]["raidRoleIcons"]["yOffset"] = 5
	E.db["unitframe"]["units"]["player"]["width"] = 220
	E.db["unitframe"]["units"]["target"]["aurabar"]["enable"] = false
	E.db["unitframe"]["units"]["target"]["buffs"]["countFont"] = "Montserrat"
	E.db["unitframe"]["units"]["target"]["buffs"]["yOffset"] = 15
	E.db["unitframe"]["units"]["target"]["castbar"]["width"] = 220
	E.db["unitframe"]["units"]["target"]["debuffs"]["countFont"] = "Montserrat"
	E.db["unitframe"]["units"]["target"]["health"]["position"] = "BOTTOMRIGHT"
	E.db["unitframe"]["units"]["target"]["health"]["text_format"] = "[health:current:shortvalue]"
	E.db["unitframe"]["units"]["target"]["health"]["xOffset"] = 3
	E.db["unitframe"]["units"]["target"]["health"]["yOffset"] = -17
	E.db["unitframe"]["units"]["target"]["height"] = 26
	E.db["unitframe"]["units"]["target"]["name"]["position"] = "TOPRIGHT"
	E.db["unitframe"]["units"]["target"]["name"]["text_format"] = "[name:short] "
	E.db["unitframe"]["units"]["target"]["name"]["xOffset"] = 7
	E.db["unitframe"]["units"]["target"]["name"]["yOffset"] = 15
	E.db["unitframe"]["units"]["target"]["power"]["detachFromFrame"] = true
	E.db["unitframe"]["units"]["target"]["power"]["detachedWidth"] = 220
	E.db["unitframe"]["units"]["target"]["power"]["enable"] = false
	E.db["unitframe"]["units"]["target"]["width"] = 220
	E.db["unitframe"]["units"]["targettarget"]["height"] = 26
	E.db["unitframe"]["units"]["targettarget"]["name"]["text_format"] = "[name:short]"
	E.db["unitframe"]["units"]["targettarget"]["power"]["enable"] = false
end
